# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: leaderboard.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ScoreLeaderboardData(betterproto.Message):
    quest_id: int = betterproto.uint64_field(1)
    score: int = betterproto.uint32_field(2)
    accountentries: List[
        "ScoreLeaderboardDataAccountEntries"
    ] = betterproto.message_field(3)
    matchentries: List["ScoreLeaderboardDataEntry"] = betterproto.message_field(5)
    leaderboard_name: str = betterproto.string_field(6)


@dataclass
class ScoreLeaderboardDataEntry(betterproto.Message):
    tag: int = betterproto.uint32_field(1)
    val: int = betterproto.uint32_field(2)


@dataclass
class ScoreLeaderboardDataAccountEntries(betterproto.Message):
    accountid: int = betterproto.uint32_field(1)
    entries: List["ScoreLeaderboardDataEntry"] = betterproto.message_field(2)
